### ISSUE TITLE
Include album release date

### ISSUE THREAD

**Issue by pedromsilvapt** [feross/last-fm#2]
Hi. Thank you for your library. I'm using it to organize my music collection by date, but sadly your method `albumInfo` does not include the `releasedate` that LastFm provides. :(

I was wondering if it was possible to add it. Even just as a string would be fine, I could parse it myself.

**Comment by tupton** [comment]
Sadly, I don't think the last.fm API even provides `releasedate`, even though [the documentation](https://www.last.fm/api/show/album.getInfo) appears to show it.

**Comment by pedromsilvapt** [comment]
Yeah, I saw it on their documentation. Too bad it isn't actually available.
