### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by daviddavo** [feross/last-fm#3]
What about users? Top Tracks/Tags/Albums/artists and other methods?

**Comment by feross** [comment]
The readme says pretty clearly:

> The most useful data on LastFM is the public music data. When building an app that incorporates music data from LastFM, lots of functionality provided by the LastFM API isn't necessary – authorizing as a user, liking tracks, adding/removing tags, getting a list of songs in the user's "library", etc.

> This package only provides the LastFM API methods that use GET requests to fetch data, making it smaller and simpler than the other LastFM libraries.

> If this matches your use case, consider using this package.
