### ISSUE TITLE
npm run build fails to minify

### ISSUE THREAD

**Issue by ejmudrak** [feross/last-fm#8]
I am unable to build this package with my React environment, let me know if you can check this out! Thanks.

More info on it:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by feross** [comment]
Sorry – I don't want to publish an ES5 version. I suggest changing your tooling so that it can handle ES6 code. It's probably uglify-js or something that can only hanle ES5 crashing on this code. I recommend `babel-minify` instead, which can handle ES6.
